apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boutique
spec:
  ingressClassName: nginx
  rules:
  - host: boutique.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
